osm/urls.py
from django.contrib import admin
from django.urls import path, include
from openstreetmap.views import MyOsmView, IndexListView, MyOsmDeleteView, ContactFormView, CenterMessagesListView, CenterMessagesDetailView, CenterMessagesDeleteView


urlpatterns=[
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', IndexListView.as_view(), name='index'),
    path('create/', MyOsmView.as_view(), name='create'),
    path('<int:pk>/delete/', MyOsmDeleteView.as_view(), name='delete'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('<int:pk>/contact/', ContactFormView.as_view(), name='contact'),
    path('messages/', CenterMessagesListView.as_view(), name='messages'),
    path('<int:pk>/message_detail/', CenterMessagesDetailView.as_view(), name='detail'),
    path('<int:pk>/message_delete/', CenterMessagesDeleteView.as_view(), name='message_delete'),

]

openstreetmap/models.py
from django.db import models
from django.shortcuts import reverse
from osm_field.fields import LatitudeField, LongitudeField, OSMField


class MyOsm(models.Model):
    location=OSMField()
    email=models.EmailField(blank=True)
    phone=models.IntegerField(null=True, blank=True)
    location_lat=LatitudeField()
    location_lon=LongitudeField()

    def __str__(self):
        return self.location


class Customer(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    message=models.TextField()
    date=models.DateField(auto_now_add=True)
    center=models.ForeignKey(MyOsm, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.name

openstreetmap/forms.py
from django import forms
from .models import MyOsm, Customer


class MyOsmForm(forms.ModelForm):
    class Meta:
        model=MyOsm
        fields='__all__'


class ContactForm(forms.ModelForm):
    class Meta:
        model=Customer
        fields='__all__'
        exclude=['center']

openstreetmap/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail, EmailMessage
from django.shortcuts import reverse
from django.template.loader import render_to_string
from django.views.generic import CreateView, ListView, DetailView, DeleteView, FormView

from .forms import MyOsmForm, ContactForm
from .models import MyOsm, Customer


class MyOsmView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = "openstreetmap/myosm_form.html"
    form_class = MyOsmForm
    model = MyOsm
    success_message = "Centre ajouté"

    def get_success_url(self):
        return reverse("index")


class MyOsmDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = "openstreetmap/myosm_delete.html"
    model = MyOsm
    success_message = 'centre supprimé'
    success_url = '/'


class IndexListView(ListView):
    model = MyOsm
    template_name = 'index.html'


class ContactFormView(SuccessMessageMixin, FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_message = 'Votre message a été envoyé'
    success_url = '/'

    # def get_center(self):
    #    center= MyOsm.objects.filter(location=self.kwargs['pk'])
    #    return center

    def form_valid(self, form):
        obj = form.save(commit=False)
        form['center'] = Customer.objects.get(id=self.kwargs['pk'])
        obj.save()
        email = form.cleaned_data.get('email')
        subject = form.cleaned_data.get('name')
        message = form.cleaned_data.get('message')
        send_mail(
            subject, message, email, ['contact@onlineformapro.com']
        )
        feedback = render_to_string('confirm.html', {'name': subject})
        email_conf = EmailMessage("Your request is in process", feedback, settings.EMAIL_HOST_USER, [email])
        email_conf.send()
        return super(ContactFormView, self).form_valid(form)


class CenterMessagesListView(LoginRequiredMixin, ListView):
    template_name = 'centermessages.html'
    model = Customer
    ordering = ['-date']


class CenterMessagesDetailView(LoginRequiredMixin, DetailView):
    template_name = 'message_detail.html'
    model = Customer


class CenterMessagesDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'message_delete.html'
    model = Customer
    success_url = '/messages/'

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}REPARE PC online{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/settings.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/preset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <!-- Favicon Icon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'onlineformapro.png' %}">
</head>
<body>
 <!-- Preloading -->
        <div class="preloader text-center">
            <div class="la-ball-circus la-2x">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
             <!-- Header 01 -->
        <header class="header_01 black_color" id="header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-2 col-sm-3 col-md-3">
                        <div class="logo">
                            <a href="{% url 'index' %}"><img src="{% static 'images/onlineformapro2.png'%}" alt=" logo"/></a>
                        </div>
                    </div>
                    <div class="col-lg-8 col-sm-7 col-md-7">
                        <nav class="mainmenu text-center">
                            <ul>
                                <li><a href="{% url 'index' %}">Home</a></li>
                                <li><a href="{% url 'contact' %}">Contact</a></li>
                                {% if not user.is_authenticated %}
                                <li><a href="{% url 'login' %}">Login</a></li>
                                {% else %}
                                <li><a href="{% url 'logout' %}">Logout</a></li>
                                <li><a href="{% url 'create' %}">Ajouter un centre</a></li>
                                    <li><a href="{% url 'messages' %}">Messages</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                    <div class="col-lg-2 col-sm-2 col-md-2">
                        <div class="navigator text-right">
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Header 01 -->


 {% include 'messages.html' %}

{% block content %}
{% endblock content %}

<!-- Footer Section -->
<footer class="footer_1">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <aside class="widget aboutwidget">
                    <a href="#"><img src="{% static 'images/onlineformapro.png' %}" alt="foot"></a>
                    <p>
                        19 rue de Praley, 70000<br>
                        Vesoul
                    </p>
                    <p>tel: 666 888 000</p>
                    <a href="{% url 'contact' %}">contact@onlineformapro.com</a>
                </aside>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section -->

<!-- Bact To To -->
<a id="backToTop" href="#" class=""><i class="fa fa-angle-double-up"></i></a>
<!-- Bact To To -->

<!-- Include All JS -->
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js ' %}"></script>
<script src="{% static 'js/modernizr.custom.js ' %}"></script>
<script src="{% static 'js/jquery.themepunch.revolution.min.js' %}"></script>
<script src="{% static 'js/jquery.themepunch.tools.min.js' %}"></script>
<!-- Rev slider Add on Start -->
<script src="{% static 'js/extensions/revolution.extension.actions.min.js' %}"></script>
<script src="{% static 'js/extensions/revolution.extension.carousel.min.js' %}"></script>
<script src="{% static 'js/extensions/revolution.extension.kenburn.min.js' %}"></script>
<script src="{% static 'js/extensions/revolution.extension.migration.min.js' %}"></script>
<script src="{% static 'js/extensions/revolution.extension.parallax.min.js' %}"></script>
<script src="{% static 'js/extensions/revolution.extension.slideanims.min.js' %}"></script>
<script src="{% static 'js/extensions/revolution.extension.layeranimation.min.js' %}"></script>
<script src="{% static 'js/extensions/revolution.extension.navigation.min.js' %}"></script>

<!-- Rev slider Add on End -->

<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'js/mixer.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/owl.carousel.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/jquery.appear.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>
<!-- Include All JS -->
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>


</body>
</html>

templates/centermessages.html
{% extends 'base.html' %}
{%  load static %}

{% block content %}
<!-- Page Banner -->
        <section class="pageBanner">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="banner_content text-center">
                            <h4><a href="/">home</a> - messages</h4>
                            <h2>Messages</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Page Banner -->
    <section class="commonSection">
            <h3>{{ customer_list.count }} messages en attente</h3>
              <div class="tbl-header mt-3">
                <table>
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Email</th>
                      <th>Message</th>
                      <th>Center</th>
                      <th>Date</th>
                    </tr>
                  </thead>
                </table>
              </div>
              <div class="tbl-content">
                <table>
                  <tbody>
                  {%  for object in object_list %}
                    <tr>
                        <td><a href="{% url 'detail' object.pk %}"><b>{{ object.name }}</b></a></td>
                        <td>{{ object.email }}</td>
                        <td><i><a href="{% url 'detail' object.pk %}">{{ object.message | slice:":20" }}...</a></i></td>
                        <td>{{ object.center }}</td>
                        <td>{{ object.date }}</td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>

    </section>


    <script>
        $(window).on("load resize ", function() {
            let scrollWidth;
            scrollWidth = $('.tbl-content').width() - $('.tbl-content table').width();
            $('.tbl-header').css({'padding-right':scrollWidth});
        }).resize();
    </script>

{% endblock %}

templates/confirm.html
Hello {{name}}

We'll get back to you as soon as possible
Thanks for your interest in Onlineformapro !

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}


{% block content %}
    <!-- Page Banner -->
        <section class="pageBanner">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="banner_content text-center">
                            <h4><a href="/">home</a> - contact</h4>
                            <h2>Contact</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Page Banner -->
        <section class="commonSection">
            <div class="container">
                    <form method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-6 offset-3">
                                {{ form | crispy }}
                                <br>
                                <button type="submit" class="btn btn-danger">Envoyer</button>
                            </div>
                        </div>
                    </form>
                </div>
        </section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% include 'slider.html' %}

    <!-- Ready Section -->
    <section class="commonSection ready_2">
        <div class="container">
            <div class="row">
                <div class="col-lg-9 col-sm-8 col-md-9">
                    <h2 class="sec_title white">Confiez-nous votre PC!</h2>
                </div>
                <div class="col-lg-3 col-sm-4 col-md-3 text-right">
                    <a class="common_btn red_bg" href="{% url 'contact' %}"><span>Contactez-nous</span></a>
                </div>
            </div>
        </div>
    </section>
    <!-- Ready Section -->

    <!-- Services Section -->
    <section class="service_section_2 commonSection">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="sec_title">Solutions globales<br> de formations & réparations</h2>
                    <p class="sec_desc">
                        Entre Digital Learning et organisme de formation reconnu, notre culture pédagogique présente
                        dans nos 21 sites (Bourgogne – Franche-Comté, Grand Est et Rhône-Alpes) nous a permis
                        d’accélérer la mutation de la formation via des solutions innovantes et adaptées notamment dans
                        les métiers de l’informatique.
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-sm-6 col-md-4">
                    <div class="icon_box_2 text-center">
                        <h3>QUI SOMMES-NOUS?</h3>
                        <p>
                            Dès sa création en 1999, ONLINEFORMAPRO s’est rapidement imposée comme une entreprise
                            innovante dans le domaine de la pédagogie inversée et pédagogie active par projet.
                        </p>
                        <div class="iconWrap">
                            <br>
                            <img src="{% static 'images/icons/center.png' %}" alt="center">
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-md-4">
                    <div class="icon_box_2 text-center">
                        <h3>REPARE PC</h3>
                        <p>
                            Ce projet initié par ONLINEFORMAPRO est né de la volonté de faire participer activement nos
                            apprenants sur des cas concrets de maintenance ou télémaintenance informatique.
                        </p>
                        <div class="iconWrap">
                            <br>
                            <img src="{% static 'images/icons/repar.png' %}" alt="repare">
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-sm-6 col-md-4">
                    <div class="icon_box_2 text-center">
                        <h3>ENVIRONNEMENT</h3>
                        <p>
                            Nos techniciens bénéficient de différents outils et logiciels afin de mener à bien leur
                            mission. Si vous souhaitez profiter de ce service, un formulaire de contact vous permet
                            d'être mis en relation avec le centre le plus proche.
                        </p>
                        <div class="iconWrap">
                            <img src="{% static 'images/icons/experts.png' %}" alt="experts">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Services Section -->

    <!-- Open Street Map -->
    <section>
        <style type="text/css">

            #map {
                height: 700px;
                width: 60%;
                margin-top: 0;
                margin-bottom: 100px;
            }
        </style>

        <div id="map">
            <!-- display map -->
        </div>
        <script type="text/javascript">

            var lat = 47.222990;
            var lon = 2.065970;

            function initMap() {

                citymap = L.map('map').setView([lat, lon], 6);

                L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {

                    attribution: '© OpenStreetMap/ODbL',
                    minZoom: 6,
                    maxZoom: 7,
                }).addTo(citymap);

                var onlineicon = L.icon({
                    iconUrl: '/static/images/icons/logo-03.svg',
                    iconSize: [28, 75],
                    popupAnchor: [0, -15]
                });


                {% for object in object_list %}
                    var marker = L.marker([{{ object.location_lat }}, {{ object.location_lon }}], {icon: onlineicon}).addTo(citymap);
                    marker.bindPopup({% include 'popup.html' %});
                {% endfor %}
            }

            window.onload = function () {
                initMap();
            };
        </script>
    </section>

    <!-- Quote Section -->

    <section class="noPadding">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 noPadding">
                    <div class="btn_link">
                        <a href="#">Plus de 20 ans à votre service</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Featured Section -->

    <section class="commonSection featured">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-12  col-md-5">
                    <div class="features_content">
                        <h4 class="sub_title">notre service</h4>
                        <h2 class="sec_title">une vraie expérience</h2>

                        <div class="singleFeature">
                            <div class="f_count">1</div>
                            <h3>centre</h3>
                            <p>
                                Vous choisissez votre centre sur la carte présente et vous laissez vos
                                coordonnées dans le formulaire proposé.
                            </p>
                            <br>
                        </div>
                        <div class="singleFeature">
                            <div class="f_count">2</div>
                            <h3>contact</h3>
                            <p>
                                Un technicien informatique "PADAWAN" prendra contact avec vous sous la supervision de
                                son coach-formateur "YODA"
                            </p>
                            <br>
                        </div>
                        <div class="singleFeature">
                            <div class="f_count">3</div>
                            <h3>diagnostic</h3>
                            <p>
                                Le diagnostic peut être réalisé à distance où vous serez alors invité à déposer votre
                                matériel dans le centre de formation le plus proche
                            </p>
                            <br>
                        </div>
                        <div class="singleFeature">
                            <div class="f_count">4</div>
                            <h3>intervention</h3>
                            <p>
                                Une fois l'intervention réalisée, vous repartez avec votre matériel, des conseils et le
                                sourire !
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 col-sm-12 col-md-7 noPaddingRight">
                    <div class="features_img">
                        <img src="{% static 'images/atwork2.jpg' %}" alt="atwork2"/>
                    </div>
                    <br>
                    <div class="features_img">
                        <img src="{% static 'images/atwork.jpg' %}" alt="atwork"/>
                        <!-- <div class="img_details">
                             <h4>Ouvert du lundi au vendredi de 09h a 19h</h4>  -->
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}

templates/map_template.html
<!-- Open Street Map -->

    <style type="text/css">

        #map {
            height: 500px;
            width:80%;
        }
    </style>


    <h3>Choose your local center</h3>

    <div id="map">
        <!-- display map -->
    </div>
    <script type="text/javascript">

        var lat = 47.222990;
        var lon = 2.065970;

        function initMap() {

            citymap = L.map('map').setView([lat, lon], 6);

            L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {

                attribution: '© OpenStreetMap/ODbL',
                minZoom: 1,
                maxZoom: 20
            }).addTo(citymap);


            {% for object in object_list %}
                var marker = L.marker([{{ object.location_lat }}, {{ object.location_lon }}]).addTo(citymap);
                marker.bindPopup( {% include 'popup.html' %} );
            {% endfor %}
        }

        window.onload = function () {
            initMap();
        };
    </script>

templates/message_delete.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}


{% block content %}
<!-- Page Banner -->
        <section class="pageBanner">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="banner_content text-center">
                            <h4><a href="/">home</a> - Messages</h4>
                            <h2>Messages</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Page Banner -->
        <section class="commonSection">
            <div class="container">
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-4 offset-4 mt-5">
                            <h4>Voulez-vous vraiment supprimer ' {{ object }} ' ?</h4>
                            <input type="submit" value="Confirmer" class="btn btn-primary">
                            <button><a href="javascript:history.go(-1)" class="btn btn-light">Retour</button>
                        </div>
                    </div>
                </form>
            </div>
    </section>
{% endblock %}

templates/message_detail.html
{%  extends 'base.html' %}

{% block content %}
     <!-- Page Banner -->
        <section class="pageBanner">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="banner_content text-center">
                            <h4><a href="/">home</a> - <a href="{% url 'messages' %}">Messages</h4>
                            <h2>{{ object.name }} </h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Page Banner -->
    <section class="commonSection">
        <div class=container>
            <div class="tbl-header">
                <table>
                  <thead>
                    <tr>
                      <th>{{ object.email }}</th>
                      <th>{{ object.date }}</th>

                        <th><a class href="{% url 'message_delete' pk=object.pk %}"><input type="submit" value="Effacer" class="btn btn-primary text-center"/></th>
                    </tr>
                  </thead>
                </table>
            </div>
            <div class="tbl-content mt-5">
                <table>
                  <tbody>
                    {{ object.message }}
                  </tbody>
                </table>
            </div>
        </div>
    </section>
{%  endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/openstreetmap/myosm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}


{% block content %}
<!-- Page Banner -->
        <section class="pageBanner">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="banner_content text-center">
                            <h4><a href="/">home</a> - Messages</h4>
                            <h2>Messages</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Page Banner -->
        <section class="commonSection">
            <div class="container">
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6 offset-4 mt-5">
                            <h4>Voulez-vous vraiment supprimer ' {{ object }} ' ?</h4>
                            <input type="submit" value="Confirmer" class="btn btn-primary">
                            <button><a href="javascript:history.go(-1)" class="btn btn-light">Retour</a></button>
                        </div>
                    </div>
                </form>
            </div>
    </section>
{% endblock %}

templates/openstreetmap/myosm_form.html
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

<!doctype html>
{% load static %}
<html lang="en">
<head>
    <title>{% block title %}REPARE PC online{% endblock title %}</title>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/settings.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/preset.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}"/>
    <link rel="icon" type="image/png" href="{% static 'onlineformapro.png' %}">
</head>
<body>
      <!-- Page Banner -->
        <section class="pageBanner">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="banner_content text-center">
                            <h4><a href="#">home</a> - centres</h4>
                            <h2>Ajouter un centre</h2>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Page Banner -->
    <section class="commonSection">
        <div class="container">
           <script type="text/javascript" src="{% static "js/vendor/jquery-2.1.0.min.js" %}"></script>
            <link href="{% static "css/vendor/leaflet.css" %}" type="text/css" media="screen" rel="stylesheet" />
            <link href="{% static "css/osm_field.css" %}" type="text/css" media="screen" rel="stylesheet" />
            <script type="text/javascript" src="{% static "js/vendor/leaflet.js" %}"></script>
            <script type="text/javascript" src="{% static "js/osm_field.js" %}"></script>
               <div class="mt-5">

                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-6 offset-3">
                                {{ form|crispy }}
                                <input type="submit" value="Save" class="btn btn-primary" />
                            </div>
                        </div>
                    </form>
                </div>
        </div>
    </section>

templates/popup.html
{% load static %}

'<img src="{% static 'onlineformapro.png' %}" alt="onlineformapro"/>'+
'<h6>{{ object.location }}</h6>'+
{% if request.user.is_authenticated %}

    '<a class href="{% url 'delete' pk=object.pk %}"><input type="submit" value="Delete" class="btn btn-danger"/>'
    {% else %}
    '<a class href="{% url 'contact' pk=object.pk %}"><input type="submit" value="Contactez-nous" class="btn btn-danger"/>'
{% endif %}